name: CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  # check-sercurity:
  #   name: '[PHP] Check security'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setting up PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: 7.4
  #         extensions: curl, json
  #         tools: symfony
  #     - name: Run check security
  #       run: symfony security:check

  check-coding-style:
    name: '[PHP] Check coding style'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: phpcs
      - name: Check coding style
        run: phpcs --standard=phpcs.xml.dist

  run-tests:
    name: '[PHP] Test with PHP${{ matrix.php }}, Laravel v${{ matrix.LARAVEL }} and ${{ matrix.dependencies }} dependencies'
    strategy:
      matrix:
        php:
          - 7.2
          - 7.3
          - 7.4
        LARAVEL:
          - 6.*
          - 7.*
          - 8.*
        dependencies:
          - highest
          - lowest
        exclude:
          - php: 7.2
            LARAVEL: 8.*

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json, mbstring
          key: cache-v1 # can be any string, change to clear the extension cache.

      - name: Cache extensions
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - name: Setting up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json, mbstring
          coverage: xdebug
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install lowest dependencies with composer
        run: |
          composer require --no-interaction --no-update "illuminate/support:${{ matrix.LARAVEL }}"
          composer update  --no-interaction --no-progress --no-suggest --prefer-lowest
        if: matrix.dependencies == 'lowest'

      - name: Install highest dependencies with composer
        run: |
          composer require --no-interaction --no-update "illuminate/support:${{ matrix.LARAVEL }}"
          composer update  --no-interaction --no-progress --no-suggest
        if: matrix.dependencies == 'highest'

      - name: Run PHPUnit
        run: php vendor/bin/phpunit --verbose --stderr --coverage-text --coverage-clover=build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: php-${{ matrix.php }}-laravel-${{ matrix.LARAVEL }}-${{ matrix.dependencies }}-dependencies
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -vvv

  coveralls-finish:
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
